server:
  port: 8080

# Configuracion de la aplicacion
application:
  security:
    jwt:
      secret-key: U2VjcmV0S2V5Rm9ySldUU2VjdXJpdHlBbmRUZXN0aW5nSXNBbHdheXNGdW4=
      expiration-time: 86400000 # 1 dia
      refresh-token:
        expiration: 604800000 # 7 dias

# Configuracion de Spring
spring:
  # Configuracion de la Base de Datos
  datasource:
    url: jdbc:mysql://localhost:3306/TrabajoFinal
    username: root
    password: Pancho09.
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuracion de JPA/Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
